version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow FastAPI to control Docker
      - ./services:/app/services
    ports:
      - "8765:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: