name: Build and Push NestOps Image
on:
    push:
      branches:
        - main
        - dev
    pull_request:
        branches: [dev, main]
jobs:
    build_and_version:
        runs-on: self-hosted

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Extract Version
              run: echo "VERSION=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Build Docker Image
              run: |
                docker build -t localhost:5000/nestops:${{ env.VERSION }} .
                docker tag localhost:5000/nestops:${{ env.VERSION }} localhost:5000/nestops:latest
      
            - name: Push Docker Image to Local Registry
              run: |
                docker push localhost:5000/nestops:${{ env.VERSION }}
                docker push localhost:5000/nestops:latest