on:
    push:
      branches:
        - main
        - dev
    pull_request:
        branches: [dev, main]
jobs:
    build_and_version:
        runs-on: self-hosted

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Extract Version
              run: echo "VERSION=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Build Docker Image
              run: |
                docker build -t nestops:${{ env.VERSION }} -f backend/Dockerfile ./backend/
                docker tag nestops:${{ env.VERSION }} nestops:latest

            - name: Save Docker Image
              run: |
                docker save nestops:${{ env.VERSION }} -o nestops${{ env.VERSION }}.tar
                docker save nestops:latest -o nestops_latest.tar